### ISSUE TITLE
translate _chapters_ko/looking_inside_neural_nets.md

### ISSUE THREAD

**Issue by rickiepark** [ml4a/ml4a.github.io#27]

**Comment by rickiepark** [comment]
@genekogan Hi, I have one question.
In 'looking_inside_neural_nets.md', what does '0op5, 1 d14 17 2ga1n' means? :)

**Comment by genekogan** [comment]
oh right :)
it's a joke / wordplay.  it looks like the sentence "Oops, I did it again" but it has numbers and letters confused, because the section is about the neural network making mistakes on characters.  if you look at the [spanish version](https://ml4a.github.io/ml4a/es/looking_inside_neural_nets/) there's a translation as well: 0op5, l0 h1ce 0tra v3z (Oops, lo hace otra vez).  obviously this doesn't work exactly that way for Korean, but if you want to try to do some wordplay like that (are there any Hangul that look like each other?) you can, but also feel free to just make something else up ;)

**Comment by rickiepark** [comment]
Ok, I got it. Thanks :)
