### ISSUE TITLE
10^80 atoms is a big lie

### ISSUE THREAD

**Issue by nuliknol** [ml4a/ml4a.github.io#53]
https://ml4a.github.io/ml4a/how_neural_networks_are_trained/

What 10^80 atoms in the universe you are talking about?

There is 5 x 10^21 atoms in a drop o water already. How many atoms would there be in Earth? The Earth is 10^6 times smaller than the Sun! How many Suns are there in the Universe? How many planets? 10^80 atoms in the Universe ? Ahahahha! I can only laugh about this.  And what if the Dark Matter has atoms too? There is no way the Universe is so small that it only has 10^80 atoms!

Brute force and random search will be the algorithms of the future when we will make our computing devices with some other type of technology than moving the electrons. Nanotechnology will help. And then, the computers will be so cheap the we will brute force everything.

**Comment by genekogan** [comment]
https://www.quora.com/How-many-atoms-are-there-in-the-entire-universe-if-for-an-instant-we-assume-the-universe-is-not-expanding

**Comment by nuliknol** [comment]
> https://www.quora.com/How-many-atoms-are-there-in-the-entire-universe-if-for-an-instant-we-assume-the-universe-is-not-expanding

they are talking about Hydrogen atoms only. Hydrogen is very unstable and it links with other elements quickly. So, 10^80 is a big lie.

**Comment by chrisschwer** [comment]
You are just shifting your argument. Originally, you decided that there most be more than 10^80 atoms. The article assumes hydrogene atoms, because they are pretty small, having only 2 protons. 
So any of the bigger atoms would reduce the number of atoms in the universe.
If a drop of water has 5*10^21 atoms, there are 2*10^58 drops of water in the universe. 

If the sun has 10^6 times the size of earth, and the earth has 10^x atoms, the sun has only 10^(x+6) atoms. 

10^a * 10^b = 10^(a**+**b)

I think that your intuitive grasp of exponentials is the issue here.

**Comment by genekogan** [comment]
this has all been very funny but i'm closing the issue now.
